name             'survivor'
maintainer       'N/A'
maintainer_email 'dorian@jaminais.fr'
license          'All rights reserved'
description      'Configure multi-hosts backups'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.1'
depends          'users'
depends          'openssh'
source_url       'https://github.com/nanassito/chef-survivor'
issues_url       'https://github.com/nanassito/chef-survivor/issues'
